### ISSUE TITLE
Assert tripping in os/apps/libc/dynamic/stat.c:ClpConvertFilePropertiesToStat ()

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#104]
assert((Properties->Permissions & (~FILE_PERMISSION_MASK)) == 0);

in the subject location is tripping when doing a "find / -name libc.so.1".

The failing assert output is something like:
 *** Assertion Failure: !"stat conversion error"
 *** File: /home/family/dlh/minocaos/minocagits/os/apps/libc/dynamic/stat.c, Line 375

(line #'s due to my hacks will likely not match anything anywhere in repository)

Diagnostics and hacks added produce output indicate the offending path, and permissions, is:
prop->perm 2148032206, FILE_PERMISSION_MASK 4095, prop->perm & (!FILE_PERMISSION_MASK) 0
stat conversion error on /dev/Devices/ACPI/PNP0A03/VEN_8086&DEV_7010/Disk/Partition2

Trying to perform:
"ls -l /dev/Devices/ACPI/PNP0A03/VEN_8086&DEV_7010/Disk/Partition2" 
from a bash shell results in an "Aborted (core dump)".

Trying to do the "ls -l" from the default minoca shell seems to result in a shell restart.

**Comment by evangreen** [comment]
Whoops, yep. We were failing to initialize all fields in PartDispatchSystemControl, around line 819. I have two fixes for this. 1) Fill out the fields in this case, and 2) Zero out the properties in the general lookup codepath so that if other drivers in the future forget to fill these out they'll get no-permissions rather than uninitialized permissions. These fixes are checked in locally.

I've promised to push soon. We're holding off on the os repository because it's a breaking change, so I have some web changes I need to complete in order to provide links to both the stable compilers and the bleeding-edge toolchain. If this is blocking you, you can zero out the properties field by inserting RtlZeroMemory(Properties, sizeof(FILE_PROPERTIES)); somewhere around line 820 of drivers/part/part.c.

**Comment by evangreen** [comment]
The added zeroing in ffe9e830eeb17bf7f472dd1bb66181e445a3a928 should fix this.
