### ISSUE TITLE
assert()s mis- placed/applied? os/apps/debug/client/dwread.c:DwarfpReadSleb128(),DwarfpReadLeb128

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#114]
There is an assert(Shift <= 64) near end of each of those routines.

I think that Shift can legitimately exceed 63 on last byte of valid values (of max bytes length) in both cases, when number is either unsigned in leb128, or is positive in case of signed (sleb128).

I believe that assert (or a replacement validity check) should instead be just at the end of the while() loop in DwarfpReadLeb128()
-and-
just before setting the sign bit on Result (i.e. inside the if) in DwarfpReadLeb128().
The limit value should probably be 63 instead of 64 as well ('<=63'), or check changed to '< 64', as I believe 64 would still be 1 bit too large a shift to fit.

Leaving them as asserts (when active) brought down the debugger for me - appears the problematic entities were of form 'static const uint64_t xxx = verybigvalueULL, but my attempts to isolate into small sample failed.  (The actual problem file is ~~33MB expanded, and gzip'd down to ~~11MB - I felt a bit large to attach/send by email/group.  I don't think my email will handle it, at least.)
namespace hashing
{
namespace detail
{
static const uint64_t k0 = 0xc3a5c85c97cb3127ULL;
static const uint64_t k1 = 0xb492b66fbe98f273ULL;
static const uint64_t k2 = 0x9ae16a3b2f90404fULL;
static const uint64_t k3 = 0xc949d7c7509e6557ULL;
}
}
readelf -s <problemfile> did not complain about the data that I could find.

**Comment by evangreen** [comment]
Hi David. Thanks for this, your sample snippet was perfect for giving me a local repro (interestingly only in C++ though).

I put those asserts there because technically those dwarf LEB128 bit values can be up to 128 bits in size, but I'm defining the DWARF_LEB128 type to be a 64-bit integer for convenience (I'd rather do integer math on it). I wanted to see if anyone was ever encoding larger values, to decide if it was necessary to convert that type to a struct and do multiprecision math.

The LEB128 values encode with a granularity of 7 bits at a time. I think the problem is 64 doesn't divide evenly by 7, so to define all 64 bits you have to have a shift of 70 (to get that single bit in the 64-70 chunk).

My plan is just to change those asserts to <= 70, rather than 64. The if statement keeps the sign extension from happening for values >= 64, which for my case is okay since I can't sign extend beyond 64 bits anyway with those types.

Does that sound reasonable?

**Comment by d-hoke** [comment]
Umm, I don't think that is correct.  

[I know that some CPUs (Alpha at least - so maybe only dead ones) will trap on shifts that are too large...  but, I guess you won't actually attempt the 70bit shift...  (Intel, on the other hand, at least used to seemingly mask the shift value to max bits allowable - don't know what ARM does.)]

but, even if shift is not too large perse (max 63bit shift for 1bit), trying to shift (inside the loop) a 7bit value 63 bits (the situation you would have just before Shift went to 70) would already have a loss of value, as you'd be throwing away the upper 6 bits - I think.  So if you're trying to catch overflows for your current 64bit limit, you'd have already missed it... and, as you'd be allowing a Shift of 70 (reached after that 63bit shift of 7bit value), the overflow would not be detected/reported - I think.

**Comment by evangreen** [comment]
I think the shift behavior on both Intel and ARM is that the bits fall off the end (which to me seems like the most logical behavior). As long as the loop stops, we shouldn't try to shift more than 64 bits.

You're right, values that used between 65-70 bits would get truncated and not fire the assert. The assert itself wasn't meant to be bulletproof, I really added it as a wakeup call to myself in case there were 128 bit numbers flying around, since I'm doing this silent truncation to 64 in order to avoid multiprecision math everywhere. If it turns out there are larger numbers flying around and I need to convert everything to multiprecision that's fine, but I wanted to see those cases first before doing a bunch of work on it.
