### ISSUE TITLE
opkg install autoconf - autoconf fails to run

### ISSUE THREAD

**Issue by d-hoke** [minoca/os#120]
running nightly pc.img from 03-29-2017 (may be irrelevant).

opkg install autoconf
(various other things installed over time)

debug /usr/bin/autom4te-4.26
yields 'Failed to execute image "/usr/bin/autom4te-2.64"'

This reached executing /usr/bin/autoconf-2.64 and having it complain when trying to obtain 'configure' script for 'file' package from 'https://github.com/file/file'.

**Comment by evangreen** [comment]
My original plan was to create packages for all the different autotools versions out there that could live side by side. I did this in the hope that autoreconfing a package you downloaded wouldn't create a bunch of extra diffs resulting from the differing versions of autotools used. Ultimately I think this won't work well because the version suffix (eg autoconf-2.64) prevents the autotools from finding each other.

I think I should clean up the autotools packages by just packaging the latest version of the tools, and dropping the version suffix (eg /usr/bin/autom4te).

The reason you can't debug autom4te-2.64 is because it is a perl script, not an executable. Unlike Linux, in Minoca the kernel does not exec shell scripts, it's left to the C library to resolve the shebang.

A (probable) workaround is to export variables so the autotools can find each other (eg `export AUTOM4TE=/usr/bin/autom4te-2.64; export AUTOCONF=/usr/bin/autoconf-2.64`, etc).

I'll leave this bug open as a reminder to do this autotools package cleanup.

**Comment by evangreen** [comment]
The packages in the nightly builds should have the updated autotools without the suffixes. Give them a try if you like, or I'll go ahead and close this in a few days.
