### ISSUE TITLE
Running make fails recognize armv7l

### ISSUE THREAD

**Issue by Melab** [minoca/os#123]
I'm trying to build Minoca on a Samsung XE303C12, but it's not for this computer (I know that this device isn't supported as a target). When I run `make`, I receive an error in `minoca.mk` that the architecture `armv7l` is not recognized.

**Comment by evangreen** [comment]
Just to clarify, you've got Linux or some other OS running on the Samsung XE303C12, and you're trying to cross compile Minoca to run on a different machine, like a PC or Raspberry Pi?

We don't have a lot of experience cross compiling on platforms other than a PC. Most people prefer that because they're usually fastest and have the most memory. That said, it should work okay, maybe with a couple build tweaks.

The first think you'll need to do is build the minoca toolchain. It's a version of GCC that runs on your Linux/Samsung device, but produces binaries for Minoca OS. We provide binary toolchains for the major OSes/arches, but since you're off the beaten path you'll need to compile your own first. Clone the third-party repository at https://gitlab.com/minoca/third-party.git and run `make tools`. That will build binutils, GCC, and a couple other tools needed to build Minoca OS. You'll need make, m4, and a working compiler for your own platform already present.

Once you have a compiler you can tweak the BUILD_ARCH filter in minoca.mk that was stopping you before. Change line 58 of minoca.mk to add armv7l to the filter. You may find other failures along the way that need a similar treatment. Alternatively, you can change line 49 of minoca.mk and hardcode it directly to `armv7`, so that we always see the build machine as ARMv7. That is obviously not a fix we could check in, but might prevent you from having to chase down more of these filters in the build scripts.

If you get stuck building third party or the OS, send me the output and I'll see what I can do.
