### ISSUE TITLE
Failed to open source file bin/rpifw: No such file or directory

### ISSUE THREAD

**Issue by vascocosta** [minoca/os#124]
I'm getting this error when trying to install onto a new partition of an SD card using msetup on a Raspberry Pi 3.

I'm using the latest rpi2.img and install.img from https://www.minocacorp.com/download/nightlies/latest-armv7.

You can see a screenshot [here](http://i.imgur.com/cuTKDCk.jpg).

**Comment by vascocosta** [comment]
Going through the code of msetup I realized that even the -p option is destructive, as in msetup apparently recreates the partitioning scheme and bails out when trying to write the new bootsector from a file that doesn't exist anymore.

I thought only -d would be destructive. Does this mean I can only install install.img on a separate card on a card reader? My goal was to install on the free space of the same sd card.

**Comment by evangreen** [comment]
Hi Vasco. Good to hear from you again! My guess is that you had the right install.img for armv7, but used `-l raspberrypi` (which is armv6) rather than `-l raspberrypi2`, which works for the armv7 raspberry pi 2 and 3. This would at least get you further in the destructive installation :)

The partition install is tricky, right now it really only works well if you have multiple installations of Minoca OS on the same disk. Installing the files to the new partition is easy enough, but most of these platforms require some sort of special boot partition sauce to make them bootable. We could add a --no-boot option, but then the user would have no way of booting into the OS they just installed on that partition. I'm open to suggestions.

**Comment by evangreen** [comment]
Closing for now, go ahead and reopen if you'd like to discuss further.
