### ISSUE TITLE
Question about the minimal UEFI implementation

### ISSUE THREAD

**Issue by Melab** [minoca/os#125]
This is about the layer of code that is meant to emulate on platforms that don't have it (i.e., Veyron, legacy BIOS, etc.). What features does it implement? What is missing? How does it provide runtime services when the OS is running (especially if there is no SMM on ARM)?

**Comment by evangreen** [comment]
Hi Melab,
Our core UEFI implementation contains basically the bare essentials needed by Minoca's boot loader to get up and running. Namely it can:
* Convey the device's memory map
* Enumerate primary storage
* Load and launch a boot EFI application from a FAT file system on that storage
* Set up a video framebuffer, which the OS uses during runtime, and provide a console during boot.
* Provide basic timer and serial services during boot
* Start and park the other cores in a multi-core system
* Hand off the ACPI tables to the OS.
* Transition to runtime via SetVirtualAddressMap and ExitBootServices

Our UEFI implementations are compiled per platform into a single blob, so they act as an encapsulation of all the platform-specific stuff so that our boot manager and OS loader don't change at all from platform to platform. Our implementation is far from complete, however. Off the top of my head big ticket items that we don't do:
* USB enumeration
* User input (so no boot menus)
* UEFI shell
* Dynamic loading of UEFI boot device drivers.
* Update capsules

UEFI runtime services are just a function table that the OS calls into. Subtracting update capsules, UEFI runtime services basically come down to Get/SetTime, Get/SetWakeupTime, and ResetSystem, which we implement per platform. I'm not a BIOS expert, but the services I think of that live behind SMM mode are more like fan control and PS/2 emulation over USB, which our implementations so far haven't had to provide.

Hope that helps. Is there a project you're thinking about?
