### ISSUE TITLE
The opkg program doesn't run.

### ISSUE THREAD

**Issue by Kripta-Studios** [minoca/os#162]
I was trying to update MinocaOS with the command ```opkg update``` and it dropped and error ```failed to download``` and ```wget returned 4```. I tried also the command ```opkg install gcc``` and of course it dropped an error that says ```Cannot install package git.```

**Comment by evangreen** [comment]
Can you describe a little about your setup? I'm wondering if you're not connected to the network, possibly because we currently only support certain ethernet controllers. What do you see as the output of `netcon`?

For reference, I was able to download the PC image off the website, fire it up in VMWare, and install things like git. Maybe this screenshot will help. I can send you my vm config if needed.

![image](https://user-images.githubusercontent.com/709517/113463978-3c61d780-93de-11eb-9b25-a874cfaafeba.png)

It might also be worth it to try and get connected to the kernel debugger if you're planning on doing any development or serious usage.

Out of curiosity, how did you come across our project?

**Comment by Kripta-Studios** [comment]
Hello @evangreen , thank you for your answer,
my output is this:
![image](https://user-images.githubusercontent.com/68393696/113624891-7e9a4b80-9660-11eb-84e0-3e2d92b67703.png)

Im in a Virtual Box virtual machine, i don't know why the MinocaOS doesn't detect my Intel Wireless-AC 9462, but Virtual Box it's connected to it. Maybe as you say is a drivers error, but im not sure because my wireless antenna is pretty common, but also i could write a driver for it if doesn't exist.

**Comment by Kripta-Studios** [comment]
> Can you describe a little about your setup? I'm wondering if you're not connected to the network, possibly because we currently only support certain ethernet controllers. What do you see as the output of `netcon`?
> 
> For reference, I was able to download the PC image off the website, fire it up in VMWare, and install things like git. Maybe this screenshot will help. I can send you my vm config if needed.
> 
> ![image](https://user-images.githubusercontent.com/709517/113463978-3c61d780-93de-11eb-9b25-a874cfaafeba.png)
> 
> It might also be worth it to try and get connected to the kernel debugger if you're planning on doing any development or serious usage.
> 
> Out of curiosity, how did you come across our project?

I wirte the answer upwards.

**Comment by evangreen** [comment]
Thanks, the info about VirtualBox helps. We don't have a driver for that wireless controller. Can you set up the VM's networking like the attached image? The "Adapter Type" setting is the important one. Other Intel PRO/1000 variants may also work.
![image](https://user-images.githubusercontent.com/709517/114281149-99b6e380-99f1-11eb-8163-aa2768fbe75b.png)

**Comment by evangreen** [comment]
Did this work for you?
