### ISSUE TITLE
More communication and knowledge storage...

### ISSUE THREAD

**Issue by drawkula** [minoca/os#31]
What about...

1. ...starting the Minoca wiki here on GitHub side by side to the code repository?
Collecting hints and tips and cheat sheets probably will pay back soon...
2. ...defining which IRC server to use for realtime communication?
IRC is well known and settled and clients grow everywhere and it perfectly works in character based environments. GitHub's text mode Gitter (Gitter bridged to IRC) is a pain and without IRC bridge it needs a running GUI. Probably I'm not the only one who does not like that.

**Comment by evangreen** [comment]
Yes, I'm up for adding documentation, hints/tips, etc. I'd prefer to have it checked in to the repository, rather than in Github's wiki, just so that I'm not married to Github (nice as they are). There's a docs folder of the repository that should do nicely. The only file I added is plain text, but I'm not opposed to Markdown either.

I'm an IRC noob. Do you have any suggestions for an IRC server?

**Comment by drawkula** [comment]
irc.freenode.net is a huge IRC network which is not always a positive property. It frequently attracts attackers.

irc.oftc.net is a well known competitor, less crowded and imho less spammed.

https://wiki.debian.org/IRC ... Lots of years ago Debian used freenode and now they're on oftc. I take that as as a statement. I'd say Debian's channels make a good neighbourhood... ;-)

And the doc/wiki topic: Changing static documentation is a hurdle... just adding some lines to a wiki is far easier. And the next one has an idea to improve the formatting and all that without `git add . ; git commit -m eureka ; git push`.

Finding a structure and a page style is not easy in the beginning, but either it busts completely or it grows and evolves until it fits.

Maybe we put the wiki question on hold for some weeks. When the community grows, I expect there will be more demand for it. Perhaps it is too early now.

**Comment by evangreen** [comment]
irc.oftc.net sounds good to me. Maybe we add a line at the bottom of the README with the official details. Maybe a little help figuring out what those details are?

Sure, I'm fine punting on the wiki question for now. Let's see how things develop and come back to it later.

**Comment by drawkula** [comment]
irc://irc.oftc.net/minoca-os now exists.

Users should register to have their names reserved but that's optional.

Users need to register if they want/need to have higher privileges.

Some users (definitely more than one) should have administrative powers and IRC related  knowledge, but that can evolve through learning by doing.

OFTC has a flash chat client at https://webchat.oftc.net/ but using a locally installed client is the better solution.

**Comment by vascocosta** [comment]
On this topic, I created a (thus far unofficial) Reddit sub for Minoca OS at https://www.reddit.com/r/MinocaOS/ mostly to share news about the operating system and possibly leverage Reddit's user base to bring new contributors to the project.

@evangreen let me know if this is was a good idea. I wouldn't mind taking care of it with an official status, if there's an interest.

**Comment by tschertel** [comment]
+1 for Reddit sub.



--
Tomás Schertel

**Comment by evangreen** [comment]
I'm pretty unaware when it comes to Reddit. @vascocosta I'm not sure what it means to make it "official", but I'm fine with you tending to it. I probably won't see things on there, so if there's something you think we should respond to, ping me.

**Comment by vascocosta** [comment]
@evangreen in reality there's no definition or need for "official" communities on Reddit. Right now I have a disclaimer on the sidebar saying "This is an unofficial Reddit community", which simply stresses it's not directly endorsed or moderated by Minoca Corp. In other words it's community driven.

That distinction was made simply because I wanted to inform you guys first. I'm more than glad to tend to it and gather a strong community around Minoca OS by sharing information about this refreshing new player into the embedded operating systems arena. Bringing new contributors to the project should come as a side-effect too, judging from my previous experience with other Reddit communities related to open-source software.

And finally, I'll keep you posted about anything there that would benefit from a more qualified answer from you.

**Comment by evangreen** [comment]
This sounds good to me! I'll leave it up to you to decide whether you'd rather keep or drop the "unofficial" qualifier.

**Comment by evangreen** [comment]
I pushed the IRC URL to the README. Closing this now, as I think we bottomed out on things.
