### ISSUE TITLE
Keyboard not working on lenovo s10-3c 

### ISSUE THREAD

**Issue by Stepanov-Sergey** [minoca/os#42]
=(

**Comment by drawkula** [comment]
On `Ideapad S10-3G` a homegrown `x86rel-2fa9de8` image booted from USB stick gave `Error FFFFFFE3`.

**Comment by evangreen** [comment]
@Stepanov-Sergey Do you see a command prompt? Out of curiosity, does plugging in a USB keyboard work?

@drawkula FFFFFFE3 is STATUS_DRIVER_FUNCTION_MISSING, which suggests to me we're in boot/fatboot/fatboot.c, line 621. This means the boot manager failed and returned back (boot/bootman/bootman.c). I'm guessing this error is printed in blue and white rather than our normal green? That seems to suggest it was FwpPcatInitializeVideo (boot/lib/pcat/int10.c) that failed to find a suitable video mode on this machine. You could try to create an image with FwVideoTextMode set to TRUE (line 387 of int10.c). It's been awhile since I've tested text mode, but firing it up in Qemu just now seemed to work.

Since we don't have those laptops in house, we'd be reliant on you guys for debugging info. If the text mode thing worked, the next step would be to figure out what video modes, if any, are enumerated on this machine, and why we couldn't find a suitable one.

**Comment by drawkula** [comment]
A real textmode!!!
[Brilliant! ](https://www.youtube.com/watch?v=028J8oUn71E)

![20161107-222537-gmt--minoca-real-text-mode](https://cloud.githubusercontent.com/assets/9768622/20078617/955e11e0-a541-11e6-8657-2e199e5729dc.png)

I need to play with this a bit... not only with the S10...

**Comment by evangreen** [comment]
@Stepanov-Sergey We just pushed some new builds to the website. If you were using images from the website, can you try the new ones? I'm not super hopeful since we never really root caused what was going on with your machine, but hey, it's worth a shot.

Without a kernel debugger, physical access to the machine, or some serious Harry Potter wizardry, there's probably not much more we can do to diagnose this.

Let me know if you're able to try the new images.
