### ISSUE TITLE
sqlite command fails on reshly built and running minoca instance

### ISSUE THREAD

**Issue by melezhik** [minoca/os#55]
Probably missed dependency on readline?

![sqlite-fail.png](https://raw.githubusercontent.com/melezhik/screenshots/master/sqlite-fail.png)

**Comment by melezhik** [comment]
and here is opkg installed list:


![opkg-list.png](https://raw.githubusercontent.com/melezhik/screenshots/master/opkg-list.png)

**Comment by evangreen** [comment]
I think you are correct. It's missing readline dependency info in both build.sh and package.sh. If I were being more granular I'd probably split out the library and the app into separate packages, since the library itself probably doesn't depend on readline, and not everyone who needs the library needs the app. But since the app and the library are in the same package, the dependency should be there.

**Comment by melezhik** [comment]
Ok, if you know what to do please close the issue, or keep it open till sqlite package got a fix.

**Comment by evangreen** [comment]
Okay, I have committed a fix for this, and will push it to third-party shortly.
