### ISSUE TITLE
su command does not work , could not read password information, permission denied

### ISSUE THREAD

**Issue by donbright** [minoca/os#60]
i have set up a qemu VM with virt-manager with a single user using 'useradd'

i got networking to work thanks to @drawkula 

then i set up sshd, generated my keyfiles and made a dir under /var/run/sshd with chmod 755 per various web tutorials on sshd

however when i ssh in as an ordinary user, i cannot seem to 'su' to do temporary work as root. i get this error
 

> -bash-4.3$ su
> su: Error: Could not read password information for user 'root': Permission denied.
> 

i dont want to ssh root@minoca , as per standard security protocols i disabled root ssh in sshd_config. 

thanks for any help!

-----

(edited to be more clear, thanks @ryniker)

**Comment by ryniker** [comment]
I ran into the same problem on a Raspberry Pi.  However, it was possible to:

ssh root@minoca

to work around this problem.

**Comment by ryniker** [comment]
>made a dir under /var/run/ssh

I had to create a sshd directory:

  mkdir /var/run/sshd
  chmod 700 /var/run/sshd

**Comment by drawkula** [comment]
> mkdir /var/run/sshd
>  chmod 700 /var/run/sshd

Someone please add this at package build time...

T.I.A.!

**Comment by ccstevens** [comment]
Thanks for reporting this one @donbright. I'm going to take a look at it next after I bottom out on the `scp` issues @drawkula reported over on Issue #58 .

**Comment by evangreen** [comment]
Hi Don. I'd guess this might be due to swiss not being a setuid binary. As root, try this sequence out:
```
rm /bin/swiss
cp -p /bin/sh /bin/swiss
chmod u+s /bin/swiss
```

Then see if you can su from a regular user up to root.

**Comment by evangreen** [comment]
@drawkula /var/run/sshd should get created by /etc/init.d/sshd, which is created in package.sh around line 61 (see the `check_privsep_dir` function). Is that not happening for you? The trouble with adding it at package time is it has to have permissions 0700, which Windows builds can't do well.

**Comment by drawkula** [comment]
@evangreen — I installed OpenSSH several times and several times needed to make `/var/run/sshd` manually. If always, I don't remember...

Just a few minutes ago...
```
opkg remove openssh
rm -rf /var/run/sshd
opkg install openssh
/etc/init.d/sshd restart
```
...complained about the missing directory. After an additional...
```
/etc/init.d/sshd start
```
The OK message came and the directory was there (with perms `755`).

I think after eventually having stopped the running instance `restart` should behave identical to `start`, so often I type `restart` instead of `start`. This probably was the culprit.

In it's initscript, the directory is set `chmod 755`... perhaps it should have been `700` there.

**Comment by evangreen** [comment]
Thanks @drawkula . I had always done /etc/init.d/sshd start, and had never tried doing /etc/init.d/sshd restart as the very first action after an install.  The check_config part apparently requires the privilege separation directory to already exist. The fix was to move the directory creation up above check_config.

If you've got third-party set up, can you try pulling down the latest, building OpenSSH.ipk, and doing the install/remove manually using that package? If not, it's not a big deal, as I'm pretty confident the fix should work.

**Comment by drawkula** [comment]
@evangreen ... A freshly built OpenSSH behaves like expected.
Thanks!

**Comment by evangreen** [comment]
Closing this puppy down.
