### ISSUE TITLE
No repo for minocacorp.com

### ISSUE THREAD

**Issue by ghost** [minoca/os#64]
1. Visit http://github.com/minoca
2. Look for the repo behind minocacorp.com
3. Visit http://gitlab.com/minoca
4. Repeat step 2

Expected results:

Able to find the sources driving minocacorp.com so that changes can be
submitted.

Actual results:

Repo for minocacorp.com content not shown

Compare to, e.g.:
- https://about.gitlab.com/ (See footer on all pages served from that domain)
- https://github.com/Microsoft/vscode-docs
- http://www.mono-project.com/docs/#page-title

... &c

**Comment by kvfi** [comment]
There is a sticky ribbon though.

**Comment by colbyrussell** [comment]
@kvfi Uh, what?

**Comment by evangreen** [comment]
Yeah, we haven't separated out the documentation part from the rest of the website. The API documentation is actually scraped from the code (periodically), so you can submit a pull request to the OS repository if you have an edit to a particular API description.

If there's documentation you'd be interested in writing that you think belongs with the source itself, you can add it to the os/docs directory and submit a pull request.

Finally, if there are edits you think would be worth making to the static web content, maybe just send me an email (evan at minocacorp dot com) and I can make the revisions manually.

Let me know if that doesn't answer your question, otherwise I'll close this in a day or so.

**Comment by colbyrussell** [comment]
Partly, this was about the current state of Minoca's public face being a really good example of the right way for an OS/kernel project to encourage and solicit contributions.  (See Minix as an example of what not to do—two and a half decades of bad decisions in community management and communication that not even millions of EUR in funding can sway.)  But minocacorp.com itself is in need of changes.

> if there are edits you think would be worth making to the static web content, maybe just send me an email (evan at minocacorp dot com) and I can make the revisions manually.

This doesn't work so well for fixing issues like "your icons look blurry on mobile".  It amounts to making a work request, which is the difference between handing someone a research paper that you've already written and asking for their approval, vs asking *them* to go write a research paper and hoping that they'll sit down and do it for you.  I don't think corrections and changes from passersby will be forthcoming if this is the approach you stick with.

I'm more than happy (really) to send any and all patches by email, rather than using GitHub's busted pull request implementation.  But I can't do that without a repo to patch against.

In addition to the way that pages on about.gitlab.com are open for change, check out how Martin Woodward is managing the content on dotnetfoundation.org (https://github.com/dotnet/home).  Although, maybe that's not a goal

**Comment by evangreen** [comment]
You're not wrong. It would be nice to open source the website, as we could then accept feedback and fixes in a formalized process. The problem for us is that initial hurdle of getting the web repository in a state that it can be open sourced. The biggest issue that comes to mind is that we need to scrub the repository for credentials. As you may have guessed, Chris and I are not web developers by trade.

I'd be willing to do this work, but I'd need to be convinced that there are real fixes and improvements people would submit. Otherwise it's effort I should be devoting to the OS. (I wonder how often about.gitlab.com takes modifications that aren't from Gitlab employees). Can you give me a sense of the scope of changes you'd be submitting?

**Comment by evangreen** [comment]
Closing this again due to lack of communication.
