### ISSUE TITLE
failed to build openssl-1.0.2h on ubuntu - ld returned 1 exit status

### ISSUE THREAD

**Issue by melezhik** [minoca/os#71]
I believe this is the _same_ issue as #69 

Here is my make log - https://gist.github.com/melezhik/60d02bed3f9d4fad57f391e5108be9e4

Somehow when `making`  target list second time fixes the issue ( in my story openssl-1.0.2h gets build in a chain of targets to build irssi dependencies, so probably other targets ( gcc-4.9.2 ?) impact the status of `make openssl-1.0.2h` )

The target list is:

```
      "all-tools",
      "pkg-config-0.29.1",
      "openssl-1.0.2h",
      "pkg-config-0.29.1",
      "libffi-3.2.1",
      "glib-2.49.6",
      "pcre-8.39",
      "libunistring-0.9.6",
      "zlib-1.2.8",
      "libxml2-2.9.4",
      "libiconv-1.14",
      "gettext-0.19.8.1",
      "mpc-0.8.1",
      "mpfr-2.4.2",
      "gmp-4.3.2",
      "ncurses-5.9",
      "gcc-4.9.2",
      "irssi-0.8.20",

```

**Comment by evangreen** [comment]
Many of these packages do already have the proper dependencies on libgcc. We don't outright fail the build attempt early because for instance on ARM libgcc is a static library, so these undefined references don't occur and the build may succeed even if libgcc_.ipk is missing.

If your automation is building packages individually you need to make sure the ordering is correct. The bottom part of the top-level Makefile in third-party attempts to lay out the overall dependencies between packages. You can also check out the ordering we use in our automation at os/tasks/build/tasks.json.

**Comment by melezhik** [comment]
Ok, Evan. I see. 

>  The bottom part of the top-level Makefile in third-party attempts to lay out the overall dependencies between packages.

So, if I get you right you only guarantee a dependency consistency if build packages a whole - `make (all)` inside $SRCROOT/third-party ? So that dependency gets installed in **right order**? And then if I want to install only a specific packages I need to ensure all the prerequisites being installed before ( actually this is what minoca-build is designed for ..  ) . Please let me know if I understand you correctly ...

**Comment by evangreen** [comment]
Yes, that's correct. If you're building in a specific package directory you'll need to build the dependencies manually. Only make all in third-party builds dependencies between packages in the right order.

Sounds like your build infrastructure will be coming in handy :)

**Comment by melezhik** [comment]
> Sounds like your build infrastructure will be coming in handy :)

Yeah. Building all the packages takes awhile, what if people want to build only specific packages, then ... :)))
