### ISSUE TITLE
WARNING: Your password has expired.

### ISSUE THREAD

**Issue by ryniker** [minoca/os#77]
After only a few days...

[ryniker@puget ~]$ ssh 192.168.100.88
ryniker@192.168.100.88's password: 
Warning: No xauth data; using fake authentication data for X11 forwarding.
X11 forwarding request failed on channel 0
WARNING: Your password has expired.
You must change your password now and login again!
passwd: warning: No shadow record of user ryniker, creating one
Old password: 
Incorrect password for ryniker
passwd: passwd: Password for ryniker is unchanged.
Connection to 192.168.100.88 closed.
[ryniker@puget ~]

I got around this by using an existing ssh connection to root to change the ryniker password
to a temporary value, then change again to the original value.

Minoca seemed to have simple security strategy - users, groups, and passwords - consistent with its "small and light" focus.

**Comment by vascocosta** [comment]
Any particular reason why you're using X11 forwarding? It requires xauth, which is not available on Minoca OS yet. I suspect the root cause for the error you're getting is simply openssh not finding xauth, instead of the password really expiring, since useradd does create a shadow record and sets the expiration date to 99999 days by default.

How did you create user ryniker initially? Did you use useradd?

**Comment by ryniker** [comment]
X11 forwarding is part of my ssh configuration because it is useful for other local targets that do use X windows.  After the messages during initial connection to the ssh daemon, there appears to be no adverse effect.

In particular, I have used multiple ssh sessions over several days before the password issue.  I used one of these sessions that was still connected (to user root) to re-establish the ryniker password.

Yes, I used groupadd and useradd to create the ryniker id as the first thing I did upon first boot of Minoca.

I observe that the permissions on /etc/shadow are 0640 instead of the 0000 I observe on linux hosts.  Is this what you see?  Could it be that some script executed by opkg did something bad?  There has not been much else done by user root, though "not much" is different from zero.

So far, this may be a singular occurrence.  I have not seen other reports of this problem, and do not know if it will recur on my host, but something undesirable happened.

**Comment by ryniker** [comment]
Clue?  I see my /etc/shadow entry for sshd has a negative value for sp_lstchg:

sshd:*:-696183:0:99999:7:::

though why that might affect the previous entry (for ryniker) is unknown.

**Comment by vascocosta** [comment]
> sshd:*:-696183:0:99999:7:::

That's interesting because that field is supposed to represent the date of the last password change in days since Jan 1, 1970.

Do you have the correct date set?

**Comment by drawkula** [comment]
@ryniker ...

> I observe that the permissions on /etc/shadow are 0640 instead of the 0000 I observe on linux hosts.

My Debians show...
```
(yeti@kumari:1)~$ cat /etc/debian_version 
8.6
(yeti@kumari:1)~$ ls -l /etc/shadow*
-rw-r----- 1 root shadow 1503 Sep 30 17:32 /etc/shadow
-rw------- 1 root root   1503 Sep 30 17:32 /etc/shadow-
```
On my current Minoca guinea pig...
```
(root@minoca:pty16)~# uname -a
Minoca minoca 0.3.0.1969-beta-debug broot-termincal-colour-experiments-d58d16c Nov 30 2016 06:42:47 i686
(root@minoca:pty16)~# ls -l /etc/shadow 
-rw-r-----  1 root root  659 Dec 01 20:56 /etc/shadow
```

**Comment by evangreen** [comment]
Hi @ryniker . That is weird. You're trying to log into root though, not sshd, right? Does your root shadow line also have a large negative number for the "days since last password change?" If so, is it the same ugly negative value or a different one? Any other accounts there with unusual values? I suppose that would explain the complaint about expiry, since -696183+99999 is still very much in the past.

We'll need to figure out what command or action caused those dates to get set so wonky. Can you remember anything you might have done that is user-account related? Repro steps would be amazing, but I'll also take a cruise around the code manipulating that field to see if I can spot something by manual inspection.

**Comment by evangreen** [comment]
From my initial inspection, I don't see any obvious mistreatment of sp_lstchg, like leaving it uninitialized. We do blindly put in the current date though for that field. I wonder if the date on your system was set to something really wacky when this occurred. -696183/365.25 = 1906, which is awfully close to a year of some kind (though I can't account for the additional 110 year discrepancy). At the very least we should probably clip that value to some saner boundaries.

Richard, let us know if you can supply any more details.

**Comment by ryniker** [comment]
>You're trying to log into root though, not sshd, right?

I tried to log in as ryniker, not root nor sshd.  The /etc/shadow record for ryniker looks good now (because the double password change restored my original password and fixed the last changed date.)  The entry for root has the same wild value -696183.  The root and ryniker accounts are the only ones that have passwords defined, and root login via ssh also fails due to the expired password problem.

Minoca apparently makes no attempt to obtain the current date from the network (Raspberry Pi has no local clock.)  I did notice after a while that the date was wrong and I set it to the current date:

~# date
date
Fri Nov 30 17:42:36 LMT 0063
~# date
date
Fri Nov 30 17:42:51 LMT 0063
~# date
date
Fri Nov 30 17:45:15 LMT 0063
~# date 120220482016
date 120220482016
Fri Dec 02 20:48:00 PST 2016
~#

I suspect this is the source of the problem - either the garbage date at boot, or the change to a correct value (passwords were set before the date was corrected; repaired after the date correction.)

Some light-weight mechanism to obtain date information from the network would be useful.  (ntpd is overkill; even ntpdate may be more than is required.)  But something needs to be done for cases where network access is unavailable, or only sporadically possible.  Would your clip notion do enough to cover this pit?

**Comment by evangreen** [comment]
You were right: on the Raspberry Pi, which lacks an RTC, we end up putting in a garbage date. I've created #78 to address that issue. With a properly "uninitialized" date, you should see the system boot somewhere near Jan 1, 2001, GMT. Then we wouldn't see any issues with the password file.

The clipping code is probably still a good idea, as clipping a date < 1970 to = 1970 would keep things sane and prevent this issue you saw with the shadow file.

The lightweight network time thing would be nice. I'd be hesitant to have it run at boot by default, because there would be a question of 1) which ntp server to ping and 2) people might see it as "phoning home". But we could think about adding a basic applet to swiss.

**Comment by ryniker** [comment]
I agree, the "lightweight network time thing" should not run by default.
However, it might be a configuration item that can be specified when
Minoca is written to boot media, as well as set up by the user after
Minoca is booted.

I bet it would be simple to use wget in a script to retrieve a current
date for rough initialization of the clock on platforms that have no
real-time-clock hardware.  

Still, the important thing is to write code that gives Minoca a benign
starting date when the platform cannot.
