### ISSUE TITLE
/usr/include/sched.h  POSIX issue

### ISSUE THREAD

**Issue by ryniker** [minoca/os#88]
POSIX specifies scheduling policies SCHED_FIFO, SCHED_RR, SCHED_SPORADIC, and  SCHED_OTHER that are optional.  What does this mean?  Python code in Modules/posixmodule.c uses an #ifdef that tests whether the sched.h header file exists; if it does, then the constants listed above are assumed to be defined.  This fails in Minoka because its sched.h does not define them.

I am not a POSIX authority, but suggest these constants should be defined in sched.h.  The optional part is implementation of the various scheduling policies.  If you have only one scheduling policy, then that is used regardless of what value is provided.  If there is more than one policy, the implementation may map the defined values to available policies however it deems best.

This is not perfect, of course.  It is possible to imagine an application that depends on FIFO thread scheduling for correct behavior, but this seems terribly fragile (just wrong, in my opinion) given the prevalence of multi-processor, multi-thread hardware.

If Minoca defines the policy symbols, this may alleviate a need to patch many programs that use POSIX threads.

**Comment by evangreen** [comment]
Are you cross-compiling or compiling on a Minoca system? I'm not sure about Python 3, but Python 2 does not cross compile because they use the interpreter they build throughout the rest of the build system. If you're trying to cross compile, are you sure there's not some pollution from your system environment? The compiler in use should be arm-none-minoca-gcc, and there shouldn't be any -I options off to system paths like /usr/include.

At https://github.com/python/cpython/blob/master/Modules/posixmodule.c#L12724 it looks like they only try to define those SCHED_* definitions if they see that they exist.

If nothing obvious is popping out I can try building Python 3 as well and see if I can spot a way to wiggle through their build system. Let me know.

**Comment by ryniker** [comment]
I tried to build Python 3.5.2 using Minoca on my target (Raspberry Pi)
platform.  This is not a cross-compilation issue.

  Minoca minoca 0.3.0.1967-beta-debug ryniker-5f082d5 Nov 29 2016 17:17:20 armv6

If the header file sched.h exists (it does) and can be compiled
successfully with the available include libraries, then Python's
configure creates the lines:

  /* Define to 1 if you have the <sched.h> header file. */
  #define HAVE_SCHED_H 1

in pyconfig.h.  This definition causes posixmodule.c to generate
references to the missing symbols:

  #ifdef HAVE_SCHED_H
      if (PyModule_AddIntMacro(m, SCHED_OTHER)) return -1;
      if (PyModule_AddIntMacro(m, SCHED_FIFO)) return -1;
      if (PyModule_AddIntMacro(m, SCHED_RR)) return -1;

Python's current (3.5.2) posixmodule.c is fifty percent longer than the
old, 2.7.11 version you referenced.  A lot has changed, here
specifically, and in Python in general.

**Comment by evangreen** [comment]
Hi Richard,
I decided to try and build Python-3.5.2. Winding my way through the issues you pointed out, plus a couple more wcs* issues (pushed to os now) I was able to get it up and building. See change [78fa378](https://gitlab.com/minoca/third-party/commit/78fa3aaff8a4ca80772d9b8dceb936e0f60bf21b) in third-party.

I know you've found basically every counterexample to this, but we really do try to avoid adding libc functions and defines unless we've also implemented them. So I decided to go with adding the ifdefs in posixmodule.c myself. I notice they actually have a [bug](http://bugs.python.org/issue27656) to the same effect and fixed it in a later [revision](https://github.com/python/cpython/commit/6482ceb24459e3fc5d4da96d6e3a2797e52723a6). So at least for now Python seems more like an outlier wrt these defines rather than an indicator of constant future pain. Hopefully someday we can actually implement these scheduler options.

Let me know if with these changes you're able to get Python 3.5 up and running.

ps- I received your USB key! Committed change b0b10af60f768a5384bb3787b8e7c5974c3343ac to get it enumerating properly in USB mass storage. I know you said not to, but I'll try to get it back to you. It may be after the holidays though depending on if the weather continues to be too foul for me to ride my bike.

**Comment by ryniker** [comment]
Now that I expect to be able to mount a USB storage device, I will rebuild Minoca from the latest source.
My last attempt to build Python 3.5.2 ended with:

if test "no" != "yes"; then \ 
    ./Programs/_freeze_importlib \
	./Lib/importlib/_bootstrap.py Python/importlib.h; \
fi
make: *** [Python/importlib.h] Error 11

The test determines this is not cross-compilation.  I do not know what Error 11 means (EAGAIN does not seem likely)  but I can learn more.

I added this hack to unistd.h:

/* Hack to implement an approximation of the dup3 facility.  Ugly                                                            
   because of possible race conditions in multi-thread environment. */

#ifndef _FCNTL_H
#include <fcntl.h>
#endif

#define dup3(oldfd, newfd, flags) ({\
    int       x, old_flags;         \
    x = dup2(oldfd, newfd) ,        \
      ( (x < 0) ? x : (old_flags = fcntl(x, F_GETFD) ,          \
                       (old_flags == -1) ?  old_flags :                 \
                       (fcntl(x, F_SETFD, old_flags | flags) == -1) ? -1 :  x) ); })

dup3 is a non-standard, linux facility, but it is a simple variation on dup2 that or's the third argument into the file descriptor flags of the new file descriptor.  I'll create a patch to do this the right way, if you want it.
My reason for the hack is it is too difficult to update an existing Minoca system. I would guess lack of link functionality is a large part of the difficulty there.

How easy do you think it would be to implement strace?

**Comment by evangreen** [comment]
Hi Richard,
Glad you're closer to getting up and running. I ran into the same problem with _freeze_importlib, you'll need change 14332642b763705a7e8955037b12def9d129dbe0 to solve that.

We do actually have dup3 at apps/libc/dynamic/fileio.c:2059, I just forgot to add a header prototype for it (whoops). I'll add that now. To get around it just add a prototype in /usr/include/unistd.h for `LIBC_API int dup3(int, int, int);`

I think most of the kernel infrastructure needed by strace is there, as in halting the process and reporting to another process. We might not have a PspTracerBreak call in the system call path, but we have it for signal delivery so adding it for system calls shouldn't be too bad. Finding the system call number and parameter pointer should also be easy. The challenging part will be figuring out a way to parse the structs in syscall.h in order for strace to understand and print out the parameters for each system call. I imagine there will be some hardcoding in strace of "I understand how to print these specific types" and then the parsing code would map those types to parameters names for each system call.

It's something we definitely wish we had as well, but we never quite need it bad enough. I suppose with the kernel debugger we're a little spoiled, as we usually end up putting in some prints or breaks in the kernel side and debugging from there.

**Comment by evangreen** [comment]
ps - I think error code 11 is actually the signal number that it died with, SIGSEGV.

**Comment by evangreen** [comment]
Going to go ahead and close this, as I think we got Python up and running without adding these defines, and the Python folks do surround these with ifdefs in a later revision anyway.
