### ISSUE TITLE
daily / weekly  images for minoca OS

### ISSUE THREAD

**Issue by melezhik** [minoca/os#95]
Hi Evan! This idea came from https://groups.google.com/forum/#!topic/minoca-dev/h8E7_s0IDLk I know @vascocosta already had some efforts for it .

it'd be nice to have a daily/or maybe/weekly minoca images in raw format. As for me, I'd like to use them in minoc-pk-test testing ( #24 ), so my requirements:

* ~ 1 GB disk space ( probably less , but not as default value set at img/Makefile  )
* ~ ALL the PRE-INSTALLED packages should  be listed AT OPKG LOCAL INDEX ( the one I get  by running `opkg list-installed`)

Without having a good test environment it's hard for me to go ahead with #24 , what do you think?

**Comment by evangreen** [comment]
Hi Alexey. I do think this is a good idea. In a few days once I've finished up what I'm working on I can try to think about how to augment the automation to push out the compiled images from our nightly builds. The pre-installed packages would be correctly listed in opkg, but I'll have to think about your 1GB image size problem a bit.

**Comment by evangreen** [comment]
Actually now that you're removing each package after installing it, do you still need 1GB or does it work with the 512MB images?

**Comment by melezhik** [comment]
Hi Evan! 1 GB were said just in case (-; , so let's start with 512 mb , I guesss it would be enough ... when this task is done , please let me know where can I get images ... thanks .

**Comment by drawkula** [comment]
@melezhik 

Making an new image using an existing one as "SDK" probably is not the fastest way but will run almost everywhere (native and VMs).

And if the staring image has `opkg`, you can use `opkg`'s superpowers to install packages on the newly `msetup`ed filesystem.

Have a look at... 
```
ROOT=/tmp/rootdir

mkdir -p \
      ${ROOT}/bin \
      ${ROOT}/etc/opkg \
      ${ROOT}/lib \
      ${ROOT}/usr/lib/opkg

cp /bin/* ${ROOT}/bin/
cp /etc/opkg/opkg.conf ${ROOT}/etc/opkg/
cp /lib/* ${ROOT}/lib/

opkg --offline-root ${ROOT} update
opkg --offline-root ${ROOT} install opkg
```
...after this, the target filesystem has all stuff needed to insttall more packages using it's own `opkg`:
```
chroot ${ROOT} opkg update
```
...install more stuff using `chroot ${ROOT} opkg  install ...

You manually can tinker things in the target FS by `chroot`ing into it with a shell:
```
echo
echo entering chroot...
echo
chroot ${ROOT} /bin/sh
```

With some additions and having `msetup`ed a fresh image before, this could be a scriptable installer or SDK or whatever you need to automate making images...

When doing such stuff on a freshly `msetup`ed image, you would not copy over the files from `/bin/` and `/lib` because `msetup` has copied them already (maybe even newer versions).

**Comment by melezhik** [comment]
HI @drawkula , thanks for pointing this. This is good scenario when preparing images for my own and  I will definitely take your notes into account when start baking images on my own. 
But my initial idea behind this issue was to have some repository of images ready to tests as close as possible to those ones Evans or others devs run their nightly tests against, so that my testing environment and theirs will be the same.

**Comment by ccstevens** [comment]
We're now publishing our latest clean builds. I need to build a read web page to list them and provide the links, but in the meantime, here's the list: 

- x86: [http://www.minocacorp.com/download/nightlies/latest-x86/Minoca-pc.zip](http://www.minocacorp.com/download/nightlies/latest-x86/Minoca-pc.zip)

- x86 UEFI [http://www.minocacorp.com/download/nightlies/latest-x86/Minoca-pcefi.zip](http://www.minocacorp.com/download/nightlies/latest-x86/Minoca-pcefi.zip)

- Galileo Board [http://www.minocacorp.com/download/nightlies/latest-x86q/Minoca-galileo.zip](http://www.minocacorp.com/download/nightlies/latest-x86q/Minoca-galileo.zip)

- RPI 2 & 3 [http://www.minocacorp.com/download/nightlies/latest-armv7/Minoca-rpi2.zip](http://www.minocacorp.com/download/nightlies/latest-armv7/Minoca-rpi2.zip)

- BeagleBone Black [http://www.minocacorp.com/download/nightlies/latest-armv7/Minoca-bbone.zip](http://www.minocacorp.com/download/nightlies/latest-armv7/Minoca-bbone.zip)

- ASUS C201 [http://www.minocacorp.com/download/nightlies/latest-armv7/Minoca-veyron.zip](http://www.minocacorp.com/download/nightlies/latest-armv7/Minoca-veyron.zip)

- Pandaboard [http://www.minocacorp.com/download/nightlies/latest-armv7/Minoca-panda.zip](http://www.minocacorp.com/download/nightlies/latest-armv7/Minoca-panda.zip)

The Raspberry Pi 1 image is not up there because it takes 4 or 5 days to build natively. We're working towards a solution to expedite that process.

**Comment by melezhik** [comment]
HI Chris! Great news, thanks.

**Comment by melezhik** [comment]
HI Chris! Great news, thanks.
